# clubs.py
# ============================================================
# Each club dict:
#   name             : Display name
#   country          : Country
#   league           : League / division
#   careers_url      : Direct URL to careers page (None = search-only)
#   teamtailor_slug  : Custom domain or slug when club uses Teamtailor
#   linkedin_company : Exact LinkedIn company name
#   linkedin_id      : LinkedIn numeric company ID
#   notes            : Scraper hints / context
# ============================================================

CLUBS = [

    # ── NETHERLANDS ──────────────────────────────────────────────────── #
    {
        "name": "PSV",
        "country": "Netherlands", "league": "Eredivisie",
        "careers_url": "https://www.psv.nl/club/organisatie/werken-bij",
        "teamtailor_slug": None,
        "linkedin_company": "PSV", "linkedin_id": "166281",
        "notes": None,
    },
    {
        "name": "Ajax",
        "country": "Netherlands", "league": "Eredivisie",
        "careers_url": "https://werkenbij.ajax.nl/",
        "teamtailor_slug": None,
        "linkedin_company": "AFC Ajax", "linkedin_id": "10928",
        "notes": None,
    },
    {
        "name": "AZ Alkmaar",
        "country": "Netherlands", "league": "Eredivisie",
        "careers_url": "https://www.werkenbijaz.nl/vacatures",
        "teamtailor_slug": None,
        "linkedin_company": "AZ", "linkedin_id": "228996",
        "notes": "Strong data culture.",
    },
    {
        "name": "Feyenoord",
        "country": "Netherlands", "league": "Eredivisie",
        "careers_url": "https://www.feyenoord.com/nl/werken-bij-feyenoord",
        "teamtailor_slug": None,
        "linkedin_company": "Feyenoord Rotterdam", "linkedin_id": "10792",
        "notes": None,
    },
    {
        "name": "FC Utrecht",
        "country": "Netherlands", "league": "Eredivisie",
        "careers_url": "https://www.fcutrecht.nl/vacatures/",
        "teamtailor_slug": None,
        "linkedin_company": "FC Utrecht", "linkedin_id": "571371",
        "notes": None,
    },

    # ── BELGIUM ──────────────────────────────────────────────────────── #
    {
        "name": "Royal Antwerp FC",
        "country": "Belgium", "league": "Jupiler Pro League",
        "careers_url": "https://www.royalantwerpfc.be/club/vacatures",
        "teamtailor_slug": None,
        "linkedin_company": "Royal Antwerp FC", "linkedin_id": "2454480",
        "notes": None,
    },
    {
        "name": "Royale Union Saint-Gilloise",
        "country": "Belgium", "league": "Jupiler Pro League",
        "careers_url": "https://rusg.brussels/en/jobs",
        "teamtailor_slug": None,
        "linkedin_company": "Royale Union Saint-Gilloise", "linkedin_id": "71388384",
        "notes": "Brighton-affiliated.",
    },
    {
        "name": "RSC Anderlecht",
        "country": "Belgium", "league": "Jupiler Pro League",
        "careers_url": "https://www.rsca.be/en/club/jobs",
        "teamtailor_slug": None,
        "linkedin_company": "RSC Anderlecht", "linkedin_id": "166614",
        "notes": None,
    },
    {
        "name": "KRC Genk",
        "country": "Belgium", "league": "Jupiler Pro League",
        "careers_url": "https://www.krcgenk.be/nl/vacatures",
        "teamtailor_slug": None,
        "linkedin_company": "KRC Genk", "linkedin_id": "1176476",
        "notes": "Strong analytics culture.",
    },
    {
        "name": "Club Brugge",
        "country": "Belgium", "league": "Jupiler Pro League",
        "careers_url": "https://jobs.clubbrugge.be/nl",
        "teamtailor_slug": None,
        "linkedin_company": "Club Brugge KV", "linkedin_id": "166516",
        "notes": None,
    },

    # ── GERMANY – Bundesliga ─────────────────────────────────────────── #
    {
        "name": "FC Bayern Munich",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://careers.fcbayern.com/go/Alle-Jobangebote-anzeigen/8774701/",
        "teamtailor_slug": None,
        "linkedin_company": "FC Bayern München", "linkedin_id": "5298",
        "notes": None,
    },
    {
        "name": "Borussia Dortmund",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://karriere.bvb.de/",  # [live]
        "teamtailor_slug": None,
        "linkedin_company": "Borussia Dortmund", "linkedin_id": "21497",
        "notes": None,
    },
    {
        "name": "Bayer 04 Leverkusen",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://www.bayer04.de/en-US/page/stellenangebote",
        "teamtailor_slug": None,
        "linkedin_company": "Bayer 04 Leverkusen", "linkedin_id": "166292",
        "notes": None,
    },
    {
        "name": "RB Leipzig",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://rbleipzig.com/de/klub/rbl/karriere",
        "teamtailor_slug": None,
        "linkedin_company": "RB Leipzig", "linkedin_id": "3628791",
        "notes": "Red Bull network.",
    },
    {
        "name": "VfB Stuttgart",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://www.vfb.de/de/1893/aktuell/jobs/jobs/",
        "teamtailor_slug": None,
        "linkedin_company": "VfB Stuttgart", "linkedin_id": "166305",
        "notes": None,
    },
    {
        "name": "Eintracht Frankfurt",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://jobapplication.hrworks.de/de?companyId=aq915e9c",  # [live]
        "teamtailor_slug": None,
        "linkedin_company": "Eintracht Frankfurt", "linkedin_id": "166296",
        "notes": None,
    },
    {
        "name": "SC Freiburg",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://jobs.scfreiburg.com/en",  # [live]
        "teamtailor_slug": None,
        "linkedin_company": "Sport-Club Freiburg", "linkedin_id": "166300",
        "notes": None,
    },
    {
        "name": "1. FSV Mainz 05",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://jobapplication.hrworks.de/de?companyId=ba8e529b",  # [live]
        "teamtailor_slug": None,
        "linkedin_company": "1. FSV Mainz 05", "linkedin_id": "166302",
        "notes": None,
    },
    {
        "name": "Borussia Mönchengladbach",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://job.borussia.de/de",  # [live]
        "teamtailor_slug": None,
        "linkedin_company": "Borussia Mönchengladbach", "linkedin_id": "166303",
        "notes": None,
    },
    {
        "name": "VfL Wolfsburg",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://www.vfl-wolfsburg.de/der-vfl/jobs/direkteinstieg",  # [live]
        "teamtailor_slug": None,
        "linkedin_company": "VfL Wolfsburg", "linkedin_id": "166299",
        "notes": "Volkswagen-owned.",
    },
    {
        "name": "FC Augsburg",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://jobs.fcaugsburg.de/de",
        "teamtailor_slug": None,
        "linkedin_company": "FC Augsburg", "linkedin_id": "1513394",
        "notes": None,
    },
    {
        "name": "Werder Bremen",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://karriere.werder.de/",
        "teamtailor_slug": None,
        "linkedin_company": "SV Werder Bremen", "linkedin_id": "166304",
        "notes": None,
    },
    {
        "name": "TSG Hoffenheim",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://www.tsg-hoffenheim.de/tsg/karriere/stellenangebote",
        "teamtailor_slug": None,
        "linkedin_company": "TSG 1899 Hoffenheim", "linkedin_id": "974798",
        "notes": "Strong analytics culture (SAP partnership).",
    },
    {
        "name": "1. FC Union Berlin",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://www.altefoersterei.berlin/en/career-OIiJ",  # [live]
        "teamtailor_slug": None,
        "linkedin_company": "1. FC Union Berlin", "linkedin_id": "6572290",
        "notes": None,
    },
    {
        "name": "FC St. Pauli",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://jobs.fcstpauli.com/de",
        "teamtailor_slug": None,
        "linkedin_company": "FC St. Pauli", "linkedin_id": "1029280",
        "notes": None,
    },
    {
        "name": "1. FC Heidenheim",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://www.fc-heidenheim.de/jobs",
        "teamtailor_slug": None,
        "linkedin_company": "1. FC Heidenheim 1846", "linkedin_id": "2490756",
        "notes": None,
    },
    {
        "name": "Holstein Kiel",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://www.holstein-kiel.de/verein/karriere/",
        "teamtailor_slug": None,
        "linkedin_company": "Holstein Kiel", "linkedin_id": "3201573",
        "notes": None,
    },
    {
        "name": "VfL Bochum",
        "country": "Germany", "league": "Bundesliga",
        "careers_url": "https://jobs.vfl-bochum.de/jobs",
        "teamtailor_slug": None,
        "linkedin_company": "VfL Bochum 1848", "linkedin_id": "166307",
        "notes": None,
    },
    {
        "name": "Hamburger SV",
        "country": "Germany", "league": "2. Bundesliga",
        "careers_url": "https://www.hsv-ev.de/verein/inhalte/jobs",  # [live]
        "teamtailor_slug": None,
        "linkedin_company": "Hamburger SV", "linkedin_id": "166295",
        "notes": None,
    },
    {
        "name": "1. FC Köln",
        "country": "Germany", "league": "2. Bundesliga",
        "careers_url": "https://fc.de/jobs",
        "teamtailor_slug": None,
        "linkedin_company": "1. FC Köln", "linkedin_id": "166293",
        "notes": None,
    },

    # ── FRANCE – Ligue 1 ─────────────────────────────────────────────── #
    {
        "name": "Paris Saint-Germain",
        "country": "France", "league": "Ligue 1",
        "careers_url": "https://parissaintgermain.wd3.myworkdayjobs.com/fr-FR/rejoigneznous",
        "teamtailor_slug": None,
        "linkedin_company": "Paris Saint-Germain", "linkedin_id": "166376",
        "notes": "Workday ATS.",
    },
    {
        "name": "Olympique de Marseille",
        "country": "France", "league": "Ligue 1",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "Olympique de Marseille", "linkedin_id": "166375",
        "notes": "Posts jobs directly on LinkedIn.",
    },
    {
        "name": "AS Monaco",
        "country": "France", "league": "Ligue 1",
        "careers_url": "https://www.asmonaco.com/fr/club/recrutement/",
        "teamtailor_slug": None,
        "linkedin_company": "AS Monaco FC", "linkedin_id": "166370",
        "notes": None,
    },
    {
        "name": "Olympique Lyonnais",
        "country": "France", "league": "Ligue 1",
        "careers_url": "https://careers.eaglefootballgroup.com/search",
        "teamtailor_slug": None,
        "linkedin_company": "Olympique Lyonnais", "linkedin_id": "166371",
        "notes": "Eagle Football Group portal.",
    },
    {
        "name": "Lille OSC",
        "country": "France", "league": "Ligue 1",
        "careers_url": "https://www.losc.fr/losc-espace-carriere",
        "teamtailor_slug": None,
        "linkedin_company": "LOSC Lille", "linkedin_id": "166372",
        "notes": None,
    },
    {
        "name": "OGC Nice",
        "country": "France", "league": "Ligue 1",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "OGC Nice", "linkedin_id": "166373",
        "notes": "INEOS-owned.",
    },
    {
        "name": "RC Lens",
        "country": "France", "league": "Ligue 1",
        "careers_url": "https://www.rclens.fr/club/emploi",
        "teamtailor_slug": None,
        "linkedin_company": "RC Lens", "linkedin_id": "1347985",
        "notes": None,
    },
    {
        "name": "Stade Rennais FC",
        "country": "France", "league": "Ligue 1",
        "careers_url": "https://www.staderennais.com/club/emplois",
        "teamtailor_slug": None,
        "linkedin_company": "Stade Rennais FC", "linkedin_id": "166374",
        "notes": None,
    },
    {
        "name": "Stade Brestois 29",
        "country": "France", "league": "Ligue 1",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "Stade Brestois 29", "linkedin_id": "3118977",
        "notes": None,
    },
    {
        "name": "Toulouse FC",
        "country": "France", "league": "Ligue 1",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "Toulouse FC", "linkedin_id": "2485756",
        "notes": "RedBird Capital ownership.",
    },
    {
        "name": "RC Strasbourg Alsace",
        "country": "France", "league": "Ligue 1",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "RC Strasbourg Alsace", "linkedin_id": "1765823",
        "notes": "BlueCo (Chelsea) ownership.",
    },
    {
        "name": "FC Nantes",
        "country": "France", "league": "Ligue 1",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "FC Nantes", "linkedin_id": "1194291",
        "notes": None,
    },
    {
        "name": "Montpellier HSC",
        "country": "France", "league": "Ligue 1",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "Montpellier Hérault Sport Club", "linkedin_id": "1500266",
        "notes": None,
    },
    {
        "name": "AJ Auxerre",
        "country": "France", "league": "Ligue 1",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "AJ Auxerre", "linkedin_id": "3203009",
        "notes": None,
    },
    {
        "name": "Le Havre AC",
        "country": "France", "league": "Ligue 1",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "Le Havre Athletic Club", "linkedin_id": "5116397",
        "notes": None,
    },
    {
        "name": "Angers SCO",
        "country": "France", "league": "Ligue 1",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "Angers SCO", "linkedin_id": "2551879",
        "notes": None,
    },
    {
        "name": "FC Metz",
        "country": "France", "league": "Ligue 1",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "FC Metz", "linkedin_id": "1481893",
        "notes": None,
    },
    {
        "name": "FC Lorient",
        "country": "France", "league": "Ligue 1",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "FC Lorient", "linkedin_id": "2453093",
        "notes": None,
    },

    # ── SPAIN – La Liga ──────────────────────────────────────────────── #
    {
        "name": "Real Madrid CF",
        "country": "Spain", "league": "La Liga",
        "careers_url": "https://jobs.realmadrid.com/",
        "teamtailor_slug": None,
        "linkedin_company": "Real Madrid C.F.", "linkedin_id": "166456",
        "notes": None,
    },
    {
        "name": "FC Barcelona",
        "country": "Spain", "league": "La Liga",
        "careers_url": "https://jobs.fcbarcelona.com/",
        "teamtailor_slug": None,
        "linkedin_company": "FC Barcelona", "linkedin_id": "166459",
        "notes": None,
    },
    {
        "name": "Valencia CF",
        "country": "Spain", "league": "La Liga",
        "careers_url": "https://www.valenciacf.com/es/club/trabaja-con-nosotros",
        "teamtailor_slug": None,
        "linkedin_company": "Valencia CF", "linkedin_id": "166457",
        "notes": None,
    },
    {
        "name": "Club Atletico de Madrid",
        "country": "Spain", "league": "La Liga",
        "careers_url": "https://www.atleticodemadrid.com/club/trabaja-con-nosotros",
        "teamtailor_slug": None,
        "linkedin_company": "Club Atlético de Madrid", "linkedin_id": "166460",
        "notes": None,
    },
    {
        "name": "Real Betis Balompie",
        "country": "Spain", "league": "La Liga",
        "careers_url": "https://www.realbetisbalompie.es/club/trabaja-con-nosotros",
        "teamtailor_slug": None,
        "linkedin_company": "Real Betis", "linkedin_id": "166461",
        "notes": None,
    },
    {
        "name": "Sevilla FC",
        "country": "Spain", "league": "La Liga",
        "careers_url": "https://www.sevillafc.es/es/club/trabaja-con-nosotros",
        "teamtailor_slug": None,
        "linkedin_company": "Sevilla FC", "linkedin_id": "166462",
        "notes": None,
    },
    {
        "name": "Real Sociedad",
        "country": "Spain", "league": "La Liga",
        "careers_url": "https://www.realsociedad.eus/es/club/trabaja-con-nosotros",
        "teamtailor_slug": None,
        "linkedin_company": "Real Sociedad", "linkedin_id": "166463",
        "notes": None,
    },
    {
        "name": "Athletic Club Bilbao",
        "country": "Spain", "league": "La Liga",
        "careers_url": "https://www.athletic-club.eus/es/club/trabaja-con-nosotros",
        "teamtailor_slug": None,
        "linkedin_company": "Athletic Club", "linkedin_id": "166464",
        "notes": None,
    },
    {
        "name": "RCD Mallorca",
        "country": "Spain", "league": "La Liga",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "RCD Mallorca", "linkedin_id": "2562993",
        "notes": None,
    },
    {
        "name": "Villarreal CF",
        "country": "Spain", "league": "La Liga",
        "careers_url": "https://www.villarealcf.es/es/club/trabaja-con-nosotros",
        "teamtailor_slug": None,
        "linkedin_company": "Villarreal CF", "linkedin_id": "166465",
        "notes": None,
    },
    {
        "name": "RC Celta de Vigo",
        "country": "Spain", "league": "La Liga",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "RC Celta de Vigo", "linkedin_id": "1229279",
        "notes": None,
    },
    {
        "name": "CA Osasuna",
        "country": "Spain", "league": "La Liga",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "CA Osasuna", "linkedin_id": "2338753",
        "notes": None,
    },
    {
        "name": "Rayo Vallecano",
        "country": "Spain", "league": "La Liga",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "Rayo Vallecano", "linkedin_id": "2529175",
        "notes": None,
    },
    {
        "name": "Girona FC",
        "country": "Spain", "league": "La Liga",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "Girona FC", "linkedin_id": "3283183",
        "notes": "City Football Group affiliate.",
    },
    {
        "name": "Deportivo Alaves",
        "country": "Spain", "league": "La Liga",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "Deportivo Alavés", "linkedin_id": "1765918",
        "notes": None,
    },
    {
        "name": "Levante UD",
        "country": "Spain", "league": "La Liga",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "Levante UD", "linkedin_id": "2469213",
        "notes": None,
    },
    {
        "name": "Real Oviedo",
        "country": "Spain", "league": "La Liga",
        "careers_url": None,
        "teamtailor_slug": None,
        "linkedin_company": "Real Oviedo", "linkedin_id": "3202850",
        "notes": None,
    },

    # ── SPAIN – La Liga 2 ────────────────────────────────────────────── #
    {
        "name": "Real Racing Santander",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "Real Racing Club de Santander", "linkedin_id": None, "notes": None,
    },
    {
        "name": "UD Las Palmas",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "UD Las Palmas", "linkedin_id": None, "notes": None,
    },
    {
        "name": "UD Almeria",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "UD Almería", "linkedin_id": None, "notes": None,
    },
    {
        "name": "Malaga CF",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "Málaga CF", "linkedin_id": None, "notes": None,
    },
    {
        "name": "CD Castellon",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "CD Castellón", "linkedin_id": None, "notes": None,
    },
    {
        "name": "RC Deportivo de La Coruna",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "RC Deportivo de La Coruña", "linkedin_id": None, "notes": None,
    },
    {
        "name": "Burgos CF",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "Burgos CF", "linkedin_id": None, "notes": None,
    },
    {
        "name": "SD Eibar",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "SD Eibar", "linkedin_id": None, "notes": None,
    },
    {
        "name": "Cordoba CF",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "Córdoba CF", "linkedin_id": None, "notes": None,
    },
    {
        "name": "FC Andorra",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "FC Andorra", "linkedin_id": None,
        "notes": "Gerard Pique ownership.",
    },
    {
        "name": "Real Sporting de Gijon",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "Real Sporting de Gijón", "linkedin_id": None, "notes": None,
    },
    {
        "name": "Albacete Balompie",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "Albacete Balompié", "linkedin_id": None, "notes": None,
    },
    {
        "name": "Granada CF",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "Granada CF", "linkedin_id": None, "notes": None,
    },
    {
        "name": "Real Valladolid CF",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "Real Valladolid CF", "linkedin_id": None,
        "notes": "Ronaldo (Brazilian) ownership.",
    },
    {
        "name": "CD Leganes",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "Club Deportivo Leganés", "linkedin_id": None, "notes": None,
    },
    {
        "name": "Cadiz CF",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "Cádiz CF", "linkedin_id": None, "notes": None,
    },
    {
        "name": "Real Zaragoza",
        "country": "Spain", "league": "La Liga 2",
        "careers_url": None, "teamtailor_slug": None,
        "linkedin_company": "Real Zaragoza", "linkedin_id": None, "notes": None,
    },

    # ── ENGLAND – Premier League ─────────────────────────────────────── #
    {
        "name": "Arsenal FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://careers.arsenal.com/jobs",
        "teamtailor_slug": "careers.arsenal.com",
        "linkedin_company": "Arsenal FC", "linkedin_id": "166529",
        "notes": "Teamtailor custom domain. Strong analytics dept.",
    },
    {
        "name": "Manchester City FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://careers.cityfootballgroup.com/",
        "teamtailor_slug": None,
        "linkedin_company": "Manchester City FC", "linkedin_id": "166526",
        "notes": "City Football Group portal.",
    },
    {
        "name": "Manchester United FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://www.manutd.com/en/club/jobs",
        "teamtailor_slug": None,
        "linkedin_company": "Manchester United", "linkedin_id": "10263",
        "notes": None,
    },
    {
        "name": "Liverpool FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://jobsearch.liverpoolfc.com/",
        "teamtailor_slug": None,
        "linkedin_company": "Liverpool FC", "linkedin_id": "166531",
        "notes": None,
    },
    {
        "name": "Aston Villa FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://careers.avfc.co.uk/jobs",
        "teamtailor_slug": "careers.avfc.co.uk",
        "linkedin_company": "Aston Villa FC", "linkedin_id": "166533",
        "notes": "Teamtailor custom domain.",
    },
    {
        "name": "AFC Bournemouth",
        "country": "England", "league": "Premier League",
        "careers_url": "https://careers.afcb.co.uk/",
        "teamtailor_slug": "careers.afcb.co.uk",
        "linkedin_company": "AFC Bournemouth", "linkedin_id": "166534",
        "notes": "Teamtailor custom domain.",
    },
    {
        "name": "Brentford FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://hiring.brentfordfc.com/jobs",
        "teamtailor_slug": "hiring.brentfordfc.com",
        "linkedin_company": "Brentford FC", "linkedin_id": "166535",
        "notes": "Teamtailor. Extremely data-driven. High priority.",
    },
    {
        "name": "Brighton & Hove Albion FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://www.brightonandhovealbion.com/careers",
        "teamtailor_slug": None,
        "linkedin_company": "Brighton & Hove Albion FC", "linkedin_id": "166536",
        "notes": "Data-driven. Tony Bloom ownership.",
    },
    {
        "name": "Chelsea FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://www.chelseafc.com/en/careers",
        "teamtailor_slug": None,
        "linkedin_company": "Chelsea FC", "linkedin_id": "166537",
        "notes": "BlueCo ownership.",
    },
    {
        "name": "Everton FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://careers.evertonfc.com/vacancies",
        "teamtailor_slug": None,
        "linkedin_company": "Everton FC", "linkedin_id": "166538",
        "notes": None,
    },
    {
        "name": "Fulham FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://www.fulhamfc.com/club/careers",
        "teamtailor_slug": None,
        "linkedin_company": "Fulham FC", "linkedin_id": "166539",
        "notes": None,
    },
    {
        "name": "Sunderland AFC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://sunderlandafc.talosats-careers.com/vacancies",
        "teamtailor_slug": None,
        "linkedin_company": "Sunderland AFC", "linkedin_id": "166540",
        "notes": None,
    },
    {
        "name": "Newcastle United FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://careers.newcastleunited.com/jobs",
        "teamtailor_slug": "careers.newcastleunited.com",
        "linkedin_company": "Newcastle United FC", "linkedin_id": "166541",
        "notes": "Teamtailor custom domain. PIF ownership.",
    },
    {
        "name": "Leeds United FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://www.leedsunited.com/en/club/careers",
        "teamtailor_slug": None,
        "linkedin_company": "Leeds United FC", "linkedin_id": "166542",
        "notes": "49ers Enterprises ownership.",
    },
    {
        "name": "Crystal Palace FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://careers.cpfc.co.uk/jobs",
        "teamtailor_slug": "careers.cpfc.co.uk",
        "linkedin_company": "Crystal Palace FC", "linkedin_id": "166543",
        "notes": "Teamtailor custom domain.",
    },
    {
        "name": "Nottingham Forest FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://careers.nottinghamforest.co.uk/jobs",
        "teamtailor_slug": "careers.nottinghamforest.co.uk",
        "linkedin_company": "Nottingham Forest FC", "linkedin_id": "166544",
        "notes": "Teamtailor custom domain.",
    },
    {
        "name": "Tottenham Hotspur FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://www.tottenhamhotspur.com/the-club/careers",
        "teamtailor_slug": None,
        "linkedin_company": "Tottenham Hotspur FC", "linkedin_id": "166545",
        "notes": None,
    },
    {
        "name": "West Ham United FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://www.whufc.com/en/the-club/careers",
        "teamtailor_slug": None,
        "linkedin_company": "West Ham United FC", "linkedin_id": "166546",
        "notes": None,
    },
    {
        "name": "Burnley FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://careers.burnleyfootballclub.com/",
        "teamtailor_slug": "careers.burnleyfootballclub.com",
        "linkedin_company": "Burnley FC", "linkedin_id": "166547",
        "notes": "Teamtailor custom domain.",
    },
    {
        "name": "Wolverhampton Wanderers FC",
        "country": "England", "league": "Premier League",
        "careers_url": "https://www.wolves.co.uk/club/vacancies/",
        "teamtailor_slug": None,
        "linkedin_company": "Wolverhampton Wanderers FC", "linkedin_id": "166548",
        "notes": None,
    },

    # ── ENGLAND – Championship ───────────────────────────────────────── #
    {"name": "Birmingham City FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Birmingham City FC", "linkedin_id": "166549", "notes": "Tom Brady / Knighthead Capital ownership."},
    {"name": "Blackburn Rovers FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Blackburn Rovers FC", "linkedin_id": "1757987", "notes": None},
    {"name": "Bristol City FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Bristol City FC", "linkedin_id": "1553887", "notes": None},
    {"name": "Charlton Athletic FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Charlton Athletic FC", "linkedin_id": "1502673", "notes": None},
    {"name": "Coventry City FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Coventry City FC", "linkedin_id": "2260984", "notes": None},
    {"name": "Derby County FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Derby County FC", "linkedin_id": "1631568", "notes": None},
    {"name": "Hull City AFC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Hull City AFC", "linkedin_id": "1739040", "notes": None},
    {"name": "Ipswich Town FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Ipswich Town FC", "linkedin_id": "1561019", "notes": None},
    {"name": "Leicester City FC", "country": "England", "league": "Championship", "careers_url": "https://www.lcfc.com/vacancies", "teamtailor_slug": None, "linkedin_company": "Leicester City FC", "linkedin_id": "166551", "notes": None},
    {"name": "Middlesbrough FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Middlesbrough FC", "linkedin_id": "1650040", "notes": None},
    {"name": "Millwall FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Millwall FC", "linkedin_id": "2270668", "notes": None},
    {"name": "Norwich City FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Norwich City FC", "linkedin_id": "166553", "notes": None},
    {"name": "Oxford United FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Oxford United FC", "linkedin_id": "4070949", "notes": None},
    {"name": "Portsmouth FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Portsmouth FC", "linkedin_id": "1680948", "notes": None},
    {"name": "Preston North End FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Preston North End FC", "linkedin_id": "2317183", "notes": None},
    {"name": "Queens Park Rangers FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Queens Park Rangers FC", "linkedin_id": "166554", "notes": None},
    {"name": "Sheffield United FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Sheffield United FC", "linkedin_id": "166555", "notes": None},
    {"name": "Sheffield Wednesday FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Sheffield Wednesday FC", "linkedin_id": "1576016", "notes": None},
    {"name": "Southampton FC", "country": "England", "league": "Championship", "careers_url": "https://www.southamptonfc.com/en/careers", "teamtailor_slug": None, "linkedin_company": "Southampton FC", "linkedin_id": "166556", "notes": None},
    {"name": "Stoke City FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Stoke City FC", "linkedin_id": "166557", "notes": None},
    {"name": "Swansea City AFC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Swansea City AFC", "linkedin_id": "1633012", "notes": None},
    {"name": "Watford FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Watford FC", "linkedin_id": "166558", "notes": "Pozzo family (same as Udinese)."},
    {"name": "West Bromwich Albion FC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "West Bromwich Albion FC", "linkedin_id": "166559", "notes": None},
    {"name": "Wrexham AFC", "country": "England", "league": "Championship", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Wrexham AFC", "linkedin_id": "4765870", "notes": "Ryan Reynolds / Rob McElhenney ownership."},

    # ── ITALY – Serie A ──────────────────────────────────────────────── #
    {"name": "Inter Milan", "country": "Italy", "league": "Serie A", "careers_url": "https://www.inter.it/it/club/lavora-con-noi", "teamtailor_slug": None, "linkedin_company": "Inter Milan", "linkedin_id": "166601", "notes": None},
    {"name": "SSC Napoli", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "SSC Napoli", "linkedin_id": "166602", "notes": None},
    {"name": "AC Milan", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "AC Milan", "linkedin_id": "166603", "notes": "RedBird Capital ownership."},
    {"name": "Juventus FC", "country": "Italy", "league": "Serie A", "careers_url": "https://www.juventus.com/it/club/careers/", "teamtailor_slug": None, "linkedin_company": "Juventus FC", "linkedin_id": "166604", "notes": None},
    {"name": "AS Roma", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "AS Roma", "linkedin_id": "166605", "notes": "Dan Friedkin ownership."},
    {"name": "Como 1907", "country": "Italy", "league": "Serie A", "careers_url": "https://www.como1907.com/en/careers", "teamtailor_slug": None, "linkedin_company": "Como 1907", "linkedin_id": "80584516", "notes": None},
    {"name": "Atalanta BC", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Atalanta BC", "linkedin_id": "166606", "notes": None},
    {"name": "SS Lazio", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "SS Lazio", "linkedin_id": "166607", "notes": None},
    {"name": "Bologna FC 1909", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Bologna FC 1909", "linkedin_id": "166608", "notes": None},
    {"name": "ACF Fiorentina", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "ACF Fiorentina", "linkedin_id": "166609", "notes": None},
    {"name": "Torino FC", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Torino FC", "linkedin_id": "166610", "notes": None},
    {"name": "Udinese Calcio", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Udinese Calcio", "linkedin_id": "166611", "notes": "Pozzo family (same as Watford)."},
    {"name": "Parma Calcio 1913", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Parma Calcio 1913", "linkedin_id": "3563267", "notes": None},
    {"name": "Genoa CFC", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Genoa CFC", "linkedin_id": "3282817", "notes": None},
    {"name": "Cagliari Calcio", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Cagliari Calcio", "linkedin_id": "3283042", "notes": None},
    {"name": "Hellas Verona FC", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Hellas Verona FC", "linkedin_id": "3202872", "notes": None},
    {"name": "US Lecce", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "US Lecce", "linkedin_id": "3282918", "notes": None},
    {"name": "US Cremonese", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "US Cremonese", "linkedin_id": "3283198", "notes": None},
    {"name": "Sassuolo Calcio", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "US Sassuolo Calcio", "linkedin_id": "2268714", "notes": None},
    {"name": "Pisa SC", "country": "Italy", "league": "Serie A", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Pisa SC", "linkedin_id": None, "notes": None},

    # ── ITALY – Serie B ──────────────────────────────────────────────── #
    {"name": "Bari", "country": "Italy", "league": "Serie B", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "SSC Bari", "linkedin_id": None, "notes": None},
    {"name": "Cesena FC", "country": "Italy", "league": "Serie B", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Cesena FC", "linkedin_id": None, "notes": None},
    {"name": "Empoli FC", "country": "Italy", "league": "Serie B", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Empoli FC", "linkedin_id": None, "notes": None},
    {"name": "Frosinone Calcio", "country": "Italy", "league": "Serie B", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Frosinone Calcio", "linkedin_id": None, "notes": None},
    {"name": "AC Monza", "country": "Italy", "league": "Serie B", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "AC Monza", "linkedin_id": None, "notes": "Berlusconi / Fininvest ownership."},
    {"name": "Palermo FC", "country": "Italy", "league": "Serie B", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Palermo FC", "linkedin_id": None, "notes": "City Football Group affiliate."},
    {"name": "Sampdoria", "country": "Italy", "league": "Serie B", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "UC Sampdoria", "linkedin_id": None, "notes": None},
    {"name": "Spezia Calcio", "country": "Italy", "league": "Serie B", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Spezia Calcio", "linkedin_id": None, "notes": None},
    {"name": "Venezia FC", "country": "Italy", "league": "Serie B", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Venezia FC", "linkedin_id": None, "notes": None},
    {"name": "Catanzaro", "country": "Italy", "league": "Serie B", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "US Catanzaro", "linkedin_id": None, "notes": None},
    {"name": "Reggiana", "country": "Italy", "league": "Serie B", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "AC Reggiana", "linkedin_id": None, "notes": None},
    {"name": "Modena FC", "country": "Italy", "league": "Serie B", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Modena FC", "linkedin_id": None, "notes": None},
    {"name": "Südtirol", "country": "Italy", "league": "Serie B", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "FC Südtirol", "linkedin_id": None, "notes": None},
    {"name": "Carrarese", "country": "Italy", "league": "Serie B", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Carrarese Calcio", "linkedin_id": None, "notes": None},
    {"name": "Mantova 1911", "country": "Italy", "league": "Serie B", "careers_url": None, "teamtailor_slug": None, "linkedin_company": "Mantova 1911", "linkedin_id": None, "notes": None},

    # ── SCOTLAND ─────────────────────────────────────────────────────── #
    {
        "name": "Celtic FC",
        "country": "Scotland", "league": "Scottish Premiership",
        "careers_url": "https://www.celticfc.com/club/careers",
        "teamtailor_slug": None,
        "linkedin_company": "Celtic FC", "linkedin_id": "166601",
        "notes": None,
    },
    {
        "name": "Rangers FC",
        "country": "Scotland", "league": "Scottish Premiership",
        "careers_url": "https://www.rangers.co.uk/club/careers",
        "teamtailor_slug": None,
        "linkedin_company": "Rangers FC", "linkedin_id": "166602",
        "notes": None,
    },

    # ── PORTUGAL ─────────────────────────────────────────────────────── #
    {
        "name": "SL Benfica",
        "country": "Portugal", "league": "Primeira Liga",
        "careers_url": "https://www.slbenfica.pt/pt-pt/clube/emprego",
        "teamtailor_slug": None,
        "linkedin_company": "Sport Lisboa e Benfica", "linkedin_id": "166700",
        "notes": None,
    },
    {
        "name": "Sporting CP",
        "country": "Portugal", "league": "Primeira Liga",
        "careers_url": "https://www.sporting.pt/pt/clube/emprego",
        "teamtailor_slug": None,
        "linkedin_company": "Sporting CP", "linkedin_id": "166701",
        "notes": None,
    },
    {
        "name": "FC Porto",
        "country": "Portugal", "league": "Primeira Liga",
        "careers_url": "https://www.fcporto.pt/pt/clube/emprego",
        "teamtailor_slug": None,
        "linkedin_company": "FC Porto", "linkedin_id": "166702",
        "notes": None,
    },

    # ── DENMARK ──────────────────────────────────────────────────────── #
    {
        "name": "FC Copenhagen",
        "country": "Denmark", "league": "Superliga",
        "careers_url": "https://www.fck.dk/klub/jobs",
        "teamtailor_slug": None,
        "linkedin_company": "FC Copenhagen", "linkedin_id": "166800",
        "notes": None,
    },
    {
        "name": "FC Midtjylland",
        "country": "Denmark", "league": "Superliga",
        "careers_url": "https://www.fcm.dk/klub/jobs",
        "teamtailor_slug": None,
        "linkedin_company": "FC Midtjylland", "linkedin_id": "166801",
        "notes": "Matthew Benham ownership (same as Brentford). Very data-driven.",
    },
]
