ANALYTICS_KEYWORDS = [
    "analyst",
    "analytics",
    "data science",
    "data scientist",
    "machine learning",
    "performance analysis",
    "performance analyst",
    "football intelligence",
    "sports science",
    "video analyst",
    "technical analyst",
    "scouting analyst",
    "recruitment analyst",
    "opposition analyst",
    "statistical",
    "data engineer",
    "data infrastructure",
    "python",
    "sql",
    "tableau",
    "power bi",
    "match analyst",
    "insight",
    "business intelligence",
    "data-driven",
    "sports analytics",
    "tracking data",
    "event data",
    "statsbomb",
    "opta",
    "wyscout",
    "instat",
    "tactical analyst",
    "head of analysis",
    "head of data",
]
